spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/chuck
    username: postgres
    password: pass
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  messages:
    basename: i18n/messages
springdoc:
  packages-to-scan: ru.elias.server
  swagger-ui:
    path: /swagger-ui
    tagsSorter: alpha
    doc-expansion: none
webclient:
  url: https://api.chucknorris.io