spring:
  datasource:
    url: jdbc:postgresql://postgres:5434/chuck
    username: postgres
    password: pass
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  messages:
    basename: i18n/messages
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 419340148161-n9f973smr4n986lnj2kphq60qh7ggf6t.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: http://localhost:8080/login/oauth2/code/google
springdoc:
  packages-to-scan: ru.elias.server
  swagger-ui:
    path: /swagger-ui
    doc-expansion: none
    oauth:
      client-id: 419340148161-n9f973smr4n986lnj2kphq60qh7ggf6t.apps.googleusercontent.com
      client-secret: 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
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html

webclient:
  url: https://api.chucknorris.io
