spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/chuck
    username: postgres
    password: pass
  messages:
    basename: i18n/messages
springdoc:
  packages-to-scan: io.elias.server
  swagger-ui:
    path: /swagger-ui
    tagsSorter: alpha
    doc-expansion: none